'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const { loadApp, RUNTIME_RELATIVE } = require('./harness.js');
const { buildPlan } = require('./fixtures.js');
const CB = require('../api/_content-bridge.js');

// COMMISSIONING -- the complete upstream path, driven end to end.
//
// A synthetic Valhalla event goes in at the domain boundary and a monday
// create_item comes out the far side, through the real eligibility rule, the
// real DTO builder, the real server validation, the real idempotency check and
// the real column mapping. The ONLY thing replaced is the HTTP call itself.
//
// NOTHING HERE IS REAL. The plan is generated by the test fixture, the athlete
// does not exist, the token is a string that is not a token, and the board is a
// recording double. No customer or beta data is involved at any point.
const ROOT = path.join(__dirname, '..');
const RUNTIME = fs.readFileSync(path.join(ROOT, RUNTIME_RELATIVE), 'utf8');
const TODAY = '2026-05-20';

const GROUP = 'group_synthetic_valhalla_evidence';

/* A recording monday. Holds items in memory keyed exactly the way the board
 * keys them -- by the Candidate ID column -- so idempotency is exercised against
 * a store that behaves like the real one rather than against a stub that always
 * says "absent". */
function fakeMonday() {
  const items = [];
  const calls = [];
  const fetch = async (url, opts) => {
    const body = JSON.parse(opts.body);
    calls.push({ url, headers: opts.headers, query: body.query, variables: body.variables });
    if (/items_page_by_column_values/.test(body.query)) {
      const want = body.variables.val[0];
      const hit = items.find(i => i.cols[CB.COL.candidateId] === want);
      return reply({ items_page_by_column_values: { items: hit ? [{ id: hit.id, name: hit.name }] : [] } });
    }
    if (/create_item/.test(body.query)) {
      const id = String(9000 + items.length);
      items.push({ id, name: body.variables.name, group: body.variables.group,
                   cols: JSON.parse(body.variables.cols) });
      return reply({ create_item: { id } });
    }
    throw new Error('unexpected query');
  };
  return { fetch, items, calls };
}
const reply = (data) => ({ ok: true, status: 200, text: async () => JSON.stringify({ data }) });

/* The environment a commissioned deployment has. Restored afterwards. */
async function configured(fn, over) {
  const keys = ['MONDAY_API_TOKEN', 'MONDAY_CONTENT_BOARD_ID', 'MONDAY_CONTENT_GROUP_ID',
                'MONDAY_CONTENT_SOURCE_LABEL', 'VVV_CONTENT_BRIDGE_ENABLED'];
  const saved = {};
  keys.forEach(k => { saved[k] = process.env[k]; });
  process.env.MONDAY_API_TOKEN = 'synthetic-not-a-real-token';
  process.env.MONDAY_CONTENT_BOARD_ID = '5102476403';
  process.env.MONDAY_CONTENT_GROUP_ID = GROUP;
  delete process.env.MONDAY_CONTENT_SOURCE_LABEL;
  process.env.VVV_CONTENT_BRIDGE_ENABLED = 'on';
  Object.assign(process.env, over || {});
  try { return await fn(); }
  finally {
    keys.forEach(k => { if (saved[k] === undefined) delete process.env[k]; else process.env[k] = saved[k]; });
  }
}

/* A synthetic block with one deliberately outstanding session. The numbers are
 * the fixture's own targets pushed to the fast edge with heart rate held inside
 * the band -- which is precisely what coachBreakthroughs() already recognises,
 * so eligibility is earned rather than asserted. */
function syntheticApp() {
  const a = loadApp({ pinnedDate: TODAY + 'T09:00:00Z' });
  a.showToast = () => {};
  buildPlan(a, { weeks: 14, startDate: a.addDays(TODAY, -28), distanceKey: 'full',
                 volume: 60, benchSec: 3 * 3600 + 15 * 60 });
  a.state.setup.benchmark = { distanceKey: 'full', timeSec: 3 * 3600 + 15 * 60 };
  a.state.setup.lthr = 172; a.state.setup.maxHR = 197;

  const dd = a.state.days.filter(d => {
    const p = a.prescriptionOf(d);
    return d.date < a.todayStr() && p && p.archetype === 'threshold_continuous';
  })[0];
  assert.ok(dd, 'the synthetic block must contain a quality session');
  const tr = a.executionPaceTarget(dd), z = a.executionHRTarget(dd);
  dd.completed = true;
  dd.actual = { km: dd.km, pace: a.secToPace(tr.fast - 4),
                hr: z && z.lo != null ? z.lo + 2 : 150, rpe: 6, notes: '' };
  return { a, dd };
}

// ---------------------------------------------------------------------------
// A / B. ELIGIBILITY
// ---------------------------------------------------------------------------
test('A. an eligible synthetic event produces exactly one Content Candidate', () => {
  const { a, dd } = syntheticApp();
  assert.ok(a.contentCandidateEligible(dd), 'the synthetic session is a breakthrough');
  const all = a.contentCandidates('founder').filter(c => c.date === dd.date);
  assert.equal(all.length, 1, 'one session, one candidate');
  assert.equal(all[0].candidateId, a.contentCandidateId(dd));
});

test('B. an ordinary session produces none', () => {
  const { a } = syntheticApp();
  const today = a.todayStr();
  const ordinary = a.state.days.filter(d => d.date < today && d.type === 'easy')[0];
  const tr = a.executionPaceTarget(ordinary);
  ordinary.completed = true;
  // On target, unremarkable: exactly the session nobody would post about.
  ordinary.actual = { km: ordinary.km, pace: a.secToPace(Math.round((tr.fast + tr.slow) / 2)),
                      hr: 140, rpe: 3, notes: '' };
  assert.equal(a.contentCandidateEligible(ordinary), false);
  assert.equal(a.contentCandidates('founder').filter(c => c.date === ordinary.date).length, 0);
});

test('B2. weak or ambiguous evidence emits nothing', () => {
  const { a, dd } = syntheticApp();
  // The athlete disowned the heart-rate data: the claim has no evidence behind it.
  dd.actual.notes = 'watch strap was loose, HR reading was nonsense';
  assert.equal(a.contentCandidateEligible(dd), false, 'doubted data is not evidence');
});

// ---------------------------------------------------------------------------
// C / D / E. THE OUTBOUND SCHEMA
// ---------------------------------------------------------------------------
test('C. the outbound DTO contains only allow-listed fields', () => {
  const { a, dd } = syntheticApp();
  const c = a.contentCandidate(dd, 'founder');
  assert.deepEqual(Object.keys(c).sort(), CB.ALLOWED.slice().sort());
  // Serialised: the app runs in its own VM realm, so two structurally identical
  // arrays are not reference-comparable.
  assert.equal(JSON.stringify(a.CONTENT_CANDIDATE_FIELDS.slice().sort()),
               JSON.stringify(CB.ALLOWED.slice().sort()),
    'runtime and server allow-lists must not drift apart');
});

test('D. forbidden athlete fields cannot leak, by construction and by refusal', async () => {
  const { a, dd } = syntheticApp();
  const c = a.contentCandidate(dd, 'founder');
  const flat = JSON.stringify(c);
  // The distinctive values the athlete logged are absent from the DTO. RPE is
  // checked by key rather than by value: a single digit legitimately appears in
  // a distance and an execution score, so a substring search would be theatre.
  for (const secret of [dd.actual.pace, String(dd.actual.hr)]) {
    assert.equal(flat.indexOf(secret), -1, 'logged value leaked: ' + secret);
  }
  for (const k of ['rpe', 'hr', 'pace', 'notes', 'feel'])
    assert.equal(k in c, false, 'prohibited key present: ' + k);
  for (const k of CB.PROHIBITED) assert.equal(k in c, false, 'prohibited key present: ' + k);

  // And the server refuses one that is tampered with in flight.
  await configured(async () => {
    const m = fakeMonday();
    const out = await CB.exportCandidate(Object.assign({}, c, { hr: 151 }), true, { fetch: m.fetch });
    assert.equal(out.ok, false);
    assert.equal(out.status, 400);
    assert.ok(out.problems.includes('prohibited_field_present'));
    assert.equal(m.calls.length, 0, 'a rejected candidate never reaches monday');
  });
});

test('E. an unknown future field cannot flow through automatically', async () => {
  const { a, dd } = syntheticApp();
  const c = a.contentCandidate(dd, 'founder');
  await configured(async () => {
    const m = fakeMonday();
    const out = await CB.exportCandidate(Object.assign({}, c, { vo2maxEstimate: 61.4 }), true,
                                         { fetch: m.fetch });
    assert.equal(out.ok, false, 'fail closed on anything not on the list');
    assert.ok(out.problems.includes('field_not_allow_listed'));
    assert.equal(m.calls.length, 0);
  });
  // A field added to a training day likewise cannot ride along.
  dd.injuryFlag = 'left achilles';
  const again = a.contentCandidate(dd, 'founder');
  assert.equal(JSON.stringify(again).indexOf('achilles'), -1);
});

// ---------------------------------------------------------------------------
// H / I. SERVER-SIDE VALIDATION AND AUTHORISATION
// ---------------------------------------------------------------------------
test('H. a malformed candidate is rejected server-side', async () => {
  await configured(async () => {
    const m = fakeMonday();
    for (const bad of [null, 'a string', [], {}, { v: 2 }]) {
      const out = await CB.exportCandidate(bad, true, { fetch: m.fetch });
      assert.equal(out.ok, false, 'accepted a malformed candidate: ' + JSON.stringify(bad));
    }
    assert.equal(m.calls.length, 0, 'nothing malformed reaches the board');
  });
});

test('I. an unauthorised caller cannot inject a candidate', async () => {
  const { a, dd } = syntheticApp();
  const c = a.contentCandidate(dd, 'founder');
  await configured(async () => {
    const m = fakeMonday();
    for (const claim of [false, undefined, null, 'true', 1, {}]) {
      const out = await CB.exportCandidate(c, claim, { fetch: m.fetch });
      assert.equal(out.status, 403, 'anything but literal true must be refused');
      assert.equal(out.code, 'not_founder');
    }
    assert.equal(m.calls.length, 0, 'an unauthorised call never touches monday');
  });
});

test('I2. the route enforcing that is the existing owner gate, not a new one', () => {
  const admin = fs.readFileSync(path.join(ROOT, 'api', 'admin-user.js'), 'utf8');
  assert.match(admin, /VVV_OWNER_USER_ID/, 'the same owner identity as every other owner route');
  assert.match(admin, /who\.uid === ownerId/, 'server-verified, never payload-claimed');
  // The runtime sends a bearer token and claims nothing about who it is.
  const region = RUNTIME.slice(RUNTIME.indexOf('var CONTENT_CANDIDATE_VERSION'),
                               RUNTIME.indexOf('/* ---------- athlete status ---------- */'));
  assert.match(region, /Authorization.*Bearer/);
  // Code, not the comment that explains where the real check lives.
  const regionCode = region.replace(/\/\*[\s\S]*?\*\//g, ' ')
                           .replace(/(^|[^:])\/\/[^\n]*/g, '$1');
  assert.equal(/VVV_OWNER_USER_ID|ownerId/.test(regionCode), false,
    'the client must not think it knows who the founder is');
});

// ---------------------------------------------------------------------------
// J / K. DESTINATION AND INITIAL STATE
// ---------------------------------------------------------------------------
test('J. the candidate lands in the right board, group and state', async () => {
  const { a, dd } = syntheticApp();
  const c = a.contentCandidate(dd, 'founder');
  await configured(async () => {
    const m = fakeMonday();
    const out = await CB.exportCandidate(c, true, { fetch: m.fetch });
    assert.equal(out.ok, true);
    assert.equal(out.created, true);
    assert.equal(m.items.length, 1, 'exactly one Candidate row');

    const it = m.items[0];
    assert.equal(m.calls[1].variables.board, '5102476403');
    assert.equal(it.group, GROUP, 'APP DATA — Valhalla Evidence, not the editorial group');
    assert.deepEqual(it.cols[CB.COL.workflowStatus], { label: 'Candidate' });
    assert.equal(it.cols[CB.COL.source], 'Valhalla');
    assert.deepEqual(it.cols[CB.COL.marketingEligible], { checked: 'true' });
    assert.equal(it.cols[CB.COL.candidateId], c.candidateId);
    assert.equal(it.cols[CB.COL.eventType], c.sessionKind);
    assert.deepEqual(it.cols[CB.COL.eventDate], { date: c.date });
    assert.equal(it.cols[CB.COL.sourceFacts], JSON.stringify(c, null, 2),
      'Source Facts is the complete candidate, verbatim, and nothing else');
    assert.ok(it.name.indexOf(c.date) === 0, 'the name identifies, it does not sell');
  });
});

test('K. no downstream preparation or publication field is populated', async () => {
  const { a, dd } = syntheticApp();
  const c = a.contentCandidate(dd, 'founder');
  await configured(async () => {
    const m = fakeMonday();
    await CB.exportCandidate(c, true, { fetch: m.fetch });
    const written = Object.keys(m.items[0].cols);

    // Exactly the seven upstream evidence columns, and nothing else. This is
    // the assertion that covers Final Caption, Publish At, Publish Channel,
    // Publish Status, Published URL and Publish Notes WITHOUT needing their
    // column ids: anything not on this list is simply never written.
    assert.deepEqual(written.slice().sort(), [
      CB.COL.candidateId, CB.COL.eventDate, CB.COL.eventType,
      CB.COL.marketingEligible, CB.COL.source, CB.COL.sourceFacts,
      CB.COL.workflowStatus
    ].sort());

    for (const [name, id] of Object.entries(CB.NEVER_WRITTEN))
      assert.equal(written.includes(id), false, 'Valhalla wrote ' + name);

    // And the whole request body mentions no publishing concept at all.
    const wire = JSON.stringify(m.calls);
    for (const word of ['publish', 'Publish', 'caption', 'Caption', 'instagram',
                        'Instagram', 'schedule', 'Approved', 'Ready to Publish'])
      assert.equal(wire.indexOf(word), -1, 'publishing vocabulary on the wire: ' + word);
  });
});

// ---------------------------------------------------------------------------
// F. IDEMPOTENCY -- the mandatory one
// ---------------------------------------------------------------------------
test('F. delivering the same candidate twice creates exactly one row', async () => {
  const { a, dd } = syntheticApp();
  const c = a.contentCandidate(dd, 'founder');
  await configured(async () => {
    const m = fakeMonday();
    const first = await CB.exportCandidate(c, true, { fetch: m.fetch });
    const second = await CB.exportCandidate(c, true, { fetch: m.fetch });

    assert.equal(first.created, true);
    assert.equal(second.created, false, 'the retry recognised the existing item');
    assert.equal(first.itemId, second.itemId, 'and returned the same row');
    assert.equal(m.items.length, 1, 'ONE row after two deliveries');
    assert.equal(second.status, 200);
  });
});

test('F2. the same session rebuilt from scratch keeps the same identity', () => {
  const { a, dd } = syntheticApp();
  const one = a.contentCandidate(dd, 'founder');
  const other = syntheticApp();
  const two = other.a.contentCandidate(other.dd, 'founder');
  assert.equal(one.candidateId, two.candidateId,
    'the idempotency key is derived from the session, not from the moment of sending');
  assert.equal(/\d{4}-\d{2}-\d{2}/.test(one.candidateId), true);
});

test('F3. a lost response is retried without duplicating', async () => {
  const { a, dd } = syntheticApp();
  const c = a.contentCandidate(dd, 'founder');
  await configured(async () => {
    const m = fakeMonday();
    // The create succeeds on the board but the caller never sees the reply.
    let swallow = true;
    const flaky = async (url, opts) => {
      const r = await m.fetch(url, opts);
      if (swallow && /create_item/.test(JSON.parse(opts.body).query)) {
        swallow = false;
        return { ok: false, status: 502, text: async () => 'gateway' };
      }
      return r;
    };
    const lost = await CB.exportCandidate(c, true, { fetch: flaky });
    assert.equal(lost.ok, false, 'the caller sees a failure');
    assert.equal(m.items.length, 1, 'but the row exists');

    const retry = await CB.exportCandidate(c, true, { fetch: m.fetch });
    assert.equal(retry.ok, true);
    assert.equal(retry.created, false, 'the retry found it rather than repeating it');
    assert.equal(m.items.length, 1, 'still ONE row');
  });
});

test('F4. the device-local record is a courtesy, not the guarantee', () => {
  // The durable identity is the Candidate ID column on the board. The client
  // store only stops a re-edited session making the same request repeatedly.
  const region = RUNTIME.slice(RUNTIME.indexOf('var CONTENT_CANDIDATE_VERSION'),
                               RUNTIME.indexOf('/* ---------- athlete status ---------- */'));
  assert.match(region, /NOT the idempotency guarantee/,
    'the code must say which mechanism is authoritative');
  const bridge = fs.readFileSync(path.join(ROOT, 'api', '_content-bridge.js'), 'utf8');
  assert.match(bridge, /findExisting/, 'the server asks the board before creating');
});

// ---------------------------------------------------------------------------
// G. FAILURE ISOLATION
// ---------------------------------------------------------------------------
test('G. a monday outage cannot fail workout or coaching processing', () => {
  const { a, dd } = syntheticApp();
  // Every transport failure mode, at the athlete's own boundary.
  const modes = [
    () => { throw new Error('offline'); },
    () => Promise.reject(new Error('dns')),
    () => Promise.resolve({ ok: false, status: 500 }),
    () => Promise.resolve({ ok: false, status: 404 })
  ];
  for (const mode of modes) {
    a.fetch = mode;
    if (a.window) a.window.fetch = mode;
    let review = null;
    assert.doesNotThrow(() => { review = a.coachPersistReview(dd); },
      'the coaching path must survive ' + mode);
    assert.ok(review, 'and still produce the review');
    assert.equal(dd.completed, true, 'the workout is still logged');
    assert.ok(dd.coachReview, 'and its review is still stored');
  }
  // The plan itself is untouched by any of it.
  assert.ok(a.state.days.length > 0);
  assert.doesNotThrow(() => a.coachAnalyse(), 'Next Move still computes');
  assert.doesNotThrow(() => a.renderTodayView(), 'TODAY still renders');
});

test('G2. an unauthorised device stops asking after one refusal', () => {
  const { a, dd } = syntheticApp();
  let sent = 0;
  const deny = () => { sent++; return Promise.resolve({ ok: false, status: 404 }); };
  a.fetch = deny; if (a.window) a.window.fetch = deny;
  a.cloudSession = { access_token: 'synthetic', user_id: 'synthetic-uid' };
  a.contentCandidateNotify(dd);
  a.contentMarkBlocked();                 // what a 404 response does
  a.contentCandidateNotify(dd);
  a.contentCandidateNotify(dd);
  assert.ok(sent <= 1, 'a beta device makes at most one refused request, not one per session');
  assert.equal(a.contentCandidateBlocked(), true);
});

test('G3. failures are observable operationally without athlete data', () => {
  const admin = fs.readFileSync(path.join(ROOT, 'api', 'admin-user.js'), 'utf8');
  const line = admin.slice(admin.indexOf("log('CONTENT_EXPORT"), admin.indexOf("return S.json(res, out.status, out.ok"));
  assert.match(line, /code=/, 'the log carries a code');
  for (const leak of ['candidate.', 'JSON.stringify(body', 'out.candidateId', 'sourceFacts'])
    assert.equal(line.indexOf(leak), -1, 'the log line must not carry ' + leak);
});

// ---------------------------------------------------------------------------
// SECURITY AND SCOPE
// ---------------------------------------------------------------------------
test('no monday credential exists anywhere a client can reach', () => {
  for (const f of ['protected/velvet-viking-valhalla.html', 'account.html', 'get.html',
                   'admin.html', 'capacitor.config.json']) {
    const src = fs.readFileSync(path.join(ROOT, f), 'utf8');
    assert.equal(/MONDAY_API_TOKEN|api\.monday\.com/.test(src), false,
      f + ' must not reference the monday credential or endpoint');
  }
  const bridge = fs.readFileSync(path.join(ROOT, 'api', '_content-bridge.js'), 'utf8');
  assert.match(bridge, /token: function\(\)/, 'the token is a getter, not a serialisable field');
});

test('the bridge is fail-closed on every missing piece of configuration', async () => {
  const { a, dd } = syntheticApp();
  const c = a.contentCandidate(dd, 'founder');
  const cases = [
    [{ VVV_CONTENT_BRIDGE_ENABLED: '' }, 'bridge_disabled'],
    [{ MONDAY_API_TOKEN: '' }, 'bridge_not_configured'],
    [{ MONDAY_CONTENT_GROUP_ID: '' }, 'bridge_group_not_configured']
  ];
  for (const [over, code] of cases) {
    await configured(async () => {
      const m = fakeMonday();
      const out = await CB.exportCandidate(c, true, { fetch: m.fetch });
      assert.equal(out.ok, false);
      assert.equal(out.code, code);
      assert.equal(m.calls.length, 0, 'nothing is sent while misconfigured');
    }, over);
  }
});

test('no athlete-facing surface was added', () => {
  const region = RUNTIME.slice(RUNTIME.indexOf('var CONTENT_CANDIDATE_VERSION'),
                               RUNTIME.indexOf('/* ---------- athlete status ---------- */'));
  const code = region.replace(/\/\*[\s\S]*?\*\//g, ' ').replace(/(^|[^:])\/\/[^\n]*/g, '$1');
  for (const ui of ['<div', '<button', 'data-action', 'showToast', 'ICONS.'])
    assert.equal(code.indexOf(ui), -1, 'the bridge must stay invisible: ' + ui);
  // Word-bounded: "resetting training paces" is coaching prose, not a settings screen.
  for (const ui of [/\bsettings?\b/i, /\bbadge\b/i, /\bnotification\b/i, /\bshare\b/i])
    assert.equal(ui.test(code), false, 'the bridge must stay invisible: ' + ui);
});

// ---------------------------------------------------------------------------
// CANDIDATE IDENTITY -- the two defects this run fixed
//
// The first pattern was vv-<date>-<archetype>. It looked stable and was not:
// the archetype DESCRIBES a session, it does not identify one. Editing a logged
// session changed the id, so the same session came back as a second monday row;
// and across two blocks the same date could reuse an id for a different session,
// silently deduping a genuinely new candidate against an old row.
// ---------------------------------------------------------------------------
test('ID1. editing the session does not change its candidate identity', () => {
  const { a, dd } = syntheticApp();
  const before = a.contentCandidateId(dd);
  // Everything a founder might correct after logging: the prescription, the
  // type, the distance, and every number they actually ran.
  dd.prescription = { v: a.PRESCRIPTION_VERSION, archetype: 'steady_tempo', params: { km: 9 } };
  dd.type = 'tempo';
  dd.km = 9;
  dd.actual.pace = a.secToPace(230);
  dd.actual.hr = 161;
  assert.equal(a.contentCandidateId(dd), before,
    'a re-prescribed session is the same session, so it is the same candidate');
});

test('ID2. two different blocks do not share an id for the same date', () => {
  const a = syntheticApp().a, b = syntheticApp().a;
  const dd = a.state.days.find(d => d.completed);
  const same = b.state.days.find(d => d.id === dd.id);
  assert.equal(a.contentCandidateId(dd), b.contentCandidateId(same),
    'the same block and date is the same candidate');
  // Now make b a genuinely different block: a different goal race.
  b.state.setup.raceDate = b.addDays(b.state.setup.raceDate, 63);
  assert.notEqual(a.contentCandidateId(dd), b.contentCandidateId(same),
    'a different block on the same date must be a different candidate');
});

test('ID3. the id carries no identity and no performance value', () => {
  const { a, dd } = syntheticApp();
  const id = a.contentCandidateId(dd);
  // Distinctive multi-character values only. A single RPE digit necessarily
  // appears somewhere in a date or a hash, so searching for it proves nothing.
  for (const leak of [dd.actual.pace, String(dd.actual.hr)])
    assert.equal(id.indexOf(leak), -1, 'id leaks ' + leak);
  assert.match(id, /^vv-[a-z0-9]+-\d{4}-\d{2}-\d{2}$/, 'shape is block key plus date');
  assert.equal(/@|uid|user/i.test(id), false, 'no account identity');
  // The date in the id is the session's own date, which is already an
  // allow-listed DTO field. The BLOCK, by contrast, is hashed: neither the
  // start date nor the goal race date appears in clear.
  const key = a.contentBlockKey();
  assert.equal(key.indexOf(a.state.setup.raceDate), -1, 'race date must be hashed');
  assert.equal(key.indexOf(a.state.setup.startDate), -1, 'start date must be hashed');
  assert.equal(key.indexOf(a.state.setup.distanceKey), -1, 'goal distance must be hashed');
  assert.ok(key.length <= 8, 'a short opaque key, not a payload');
});

test('ID4. the id is deterministic -- same state, same id, every time', () => {
  const { a, dd } = syntheticApp();
  const ids = new Set();
  for (let i = 0; i < 5; i++) ids.add(a.contentCandidateId(dd));
  assert.equal(ids.size, 1);
  // and it survives a reload of the same plan
  const again = syntheticApp();
  assert.equal(again.a.contentCandidateId(again.dd), a.contentCandidateId(dd));
});

test('ID5. an edited session does not create a second monday row', async () => {
  const { a, dd } = syntheticApp();
  const first = a.contentCandidate(dd, 'founder');
  await configured(async () => {
    const m = fakeMonday();
    await CB.exportCandidate(first, true, { fetch: m.fetch });
    // The founder corrects the session and it is reprocessed.
    dd.type = 'tempo';
    dd.prescription = { v: a.PRESCRIPTION_VERSION, archetype: 'steady_tempo', params: { km: 9 } };
    const edited = a.contentCandidate(dd, 'founder');
    const out = await CB.exportCandidate(edited, true, { fetch: m.fetch });
    assert.equal(out.created, false, 'the edit resolved to the existing candidate');
    assert.equal(m.items.length, 1, 'ONE row, not two');
  });
});
