-- ===========================================================================
-- WHAT THE ATHLETE AGREED TO, AND WHEN
--
-- Two things a paying customer has to be asked, both of which have to be
-- provable afterwards, and neither of which is Article 9 health consent:
--
--   TERMS ACCEPTANCE          which version of the Terms was in front of them
--                             when they agreed, and on which surface.
--   IMMEDIATE-START           the acknowledgement that they are asking us to
--   ACKNOWLEDGEMENT           begin a digital service during the statutory
--                             cancellation period for a distance contract, and
--                             that beginning it affects that right.
--
-- ONE TABLE, TWO KINDS, BECAUSE THEY ARE THE SAME SHAPE: an authenticated
-- athlete, a named version of some wording, a decision, and the moment it was
-- made. Two tables would be two sets of policies, two audit stories and two
-- places to look. agreement_type discriminates them and the check constraint
-- keeps the vocabulary closed.
--
-- WHAT IS DELIBERATELY NOT HERE
--
--   ARTICLE 9 HEALTH CONSENT. It stays in public.health_data_consent, where it
--   already is and where it is already proven. Explicit consent to process
--   special-category data is a different legal act from accepting contractual
--   terms, it is withdrawable on its own, and folding the two together would
--   make "did they consent to health processing" unanswerable without also
--   asking about Terms. They are separate because they ARE separate.
--
--   PRIVACY. A privacy notice is INFORMATION, not a decision. There is no
--   "I consent to the Privacy Policy" row here and there must never be one:
--   asking somebody to consent to being informed is both meaningless and, by
--   implying consent is the lawful basis, actively misleading. Which version
--   was presented alongside an accepted Terms is recorded on the Terms row as
--   context -- privacy_version -- because "what were they shown" is a fair
--   question. That is a record of presentation, not of agreement.
--
--   MARKETING CONSENT. Not implemented, not needed, and not being smuggled in
--   as a third agreement_type against the day somebody wants it.
--
-- APPEND-ONLY, for the same reason health consent is: a single mutable row
-- answers "do they agree now" and destroys "did they agree on the day the
-- contract was formed", which is the question that actually gets asked. The
-- current state is the newest row of its type; everything behind it is history.
--
-- WHERE IT SITS IN THE ORDER. After supabase-security-posture.sql (file 10),
-- which asserts that every table in public has row-level security enabled --
-- this one is created with RLS on, so re-running 10 afterwards passes.
--
-- Safe to re-run.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- STEP 1 -- THE RECORD
--
-- agreement_version is the point of the design, exactly as consent_version is
-- next door. Agreement is recorded against a NAMED VERSION of the wording, not
-- against whatever happened to be on the screen. When the wording changes -- and
-- both the Terms and the solicitor-approved immediate-start acknowledgement may
-- yet be revised -- the constant changes, every stored agreement to the previous
-- version stops counting, and the athlete is asked again. No migration, no
-- backfill, and no possibility of a stored "yes" being quietly re-pointed at
-- wording the athlete never saw.
--
-- decided_at is written by the client for the same reason it is on health
-- consent: the decision happens on the device, and the audit should record when
-- the athlete decided rather than when the row reached the database.
-- created_at keeps the server's own view, so the two can be compared.
--
-- surface records WHERE the agreement was given -- 'checkout', 'account',
-- 'signup'. Not decoration: "was this presented at the point of payment or
-- buried in a settings screen" is precisely what an adjudicator asks about an
-- acknowledgement that affects a cancellation right.
-- ---------------------------------------------------------------------------
create table if not exists public.account_agreements (
  id                 bigint generated by default as identity primary key,
  user_id            uuid        not null references auth.users(id) on delete cascade,

  agreement_type     text        not null
                       check (agreement_type in ('terms', 'immediate_start')),
  agreement_version  text        not null,

  -- 'accepted' is the only affirmative value. 'declined' exists because an
  -- athlete who reads the immediate-start wording and says no has made a
  -- decision worth recording, and because a decision vocabulary with only one
  -- member is not a decision.
  decision           text        not null check (decision in ('accepted', 'declined')),

  -- Where they were standing when they agreed.
  surface            text        not null
                       check (surface in ('checkout', 'account', 'signup', 'app')),

  -- Context, not agreement. Which privacy notice was presented alongside; and,
  -- for an immediate-start acknowledgement, which offer it was given against,
  -- because the acknowledgement is about beginning THIS service on THIS
  -- purchase.
  privacy_version    text,
  offer_code         text        check (offer_code in ('STANDARD_MONTHLY','STANDARD_YEARLY')),

  decided_at         timestamptz not null,
  created_at         timestamptz not null default now()
);

-- The only query the product makes: this athlete's most recent decision of a
-- given kind.
create index if not exists account_agreements_user_type_decided_idx
  on public.account_agreements (user_id, agreement_type, decided_at desc);

alter table public.account_agreements enable row level security;


-- ---------------------------------------------------------------------------
-- STEP 2 -- ROW-LEVEL SECURITY
--
-- The same two policies health_data_consent carries, for the same reasons.
--
--   SELECT own rows -- an athlete may see what they agreed to.
--   INSERT own rows -- with WITH CHECK pinning user_id to the caller, so no
--   client can write an agreement naming somebody else. A forged "they
--   accepted" row is worse than no row at all: it is evidence that says the
--   opposite of the truth.
--
-- NO UPDATE POLICY AND NO DELETE POLICY, deliberately. Under RLS, a command
-- with no policy is denied to every browser role. An append-only record of what
-- somebody agreed to, which that same somebody can rewrite, is not evidence.
--
-- (select auth.uid()) rather than a bare auth.uid(), for the InitPlan reason
-- written out in supabase-security-posture.sql.
-- ---------------------------------------------------------------------------
drop policy if exists "own agreements: select" on public.account_agreements;
drop policy if exists "own agreements: insert" on public.account_agreements;

create policy "own agreements: select" on public.account_agreements
  for select using ((select auth.uid()) = user_id);

create policy "own agreements: insert" on public.account_agreements
  for insert with check ((select auth.uid()) = user_id);


-- ---------------------------------------------------------------------------
-- STEP 3 -- REFUSE IF THE POSTURE IS WRONG
--
-- Everything above is idempotent, so the value of re-running this file is
-- entirely in what it CHECKS. It raises rather than repairs: a posture that
-- drifted did so for a reason, and silently rewriting it hides the reason.
-- ---------------------------------------------------------------------------
do $$
declare v_rls boolean; v_bad text; v_open int;
begin
  select relrowsecurity from pg_class
   where oid = 'public.account_agreements'::regclass into v_rls;
  if not coalesce(v_rls, false) then
    raise exception using errcode = 'raise_exception',
      message = 'account_agreements has row-level security OFF. Nothing has been changed.';
  end if;

  select string_agg(policyname || ' (' || cmd || ')', ', ')
    from pg_policies
   where schemaname = 'public' and tablename = 'account_agreements'
     and cmd in ('UPDATE', 'DELETE', 'ALL')
    into v_bad;
  if v_bad is not null then
    raise exception using errcode = 'raise_exception',
      message = 'account_agreements must be append-only, but these policies allow '
             || 'rewriting it: ' || v_bad || '. Nothing has been changed.';
  end if;

  select count(*)
    from pg_policies
   where schemaname = 'public' and tablename = 'account_agreements'
     and coalesce(qual, '') || coalesce(with_check, '') not like '%auth.uid()%'
    into v_open;
  if v_open > 0 then
    raise exception using errcode = 'raise_exception',
      message = 'account_agreements has ' || v_open || ' policy/policies not scoped to '
             || 'the calling athlete. Nothing has been changed.';
  end if;
end $$;


-- ---------------------------------------------------------------------------
-- STEP 4 -- VERIFY. Read-only.
--
-- Expect: rls = true, exactly two policies (one SELECT, one INSERT), and no
-- rows at all before the first athlete reaches checkout.
-- ---------------------------------------------------------------------------
select
  (select relrowsecurity from pg_class where oid='public.account_agreements'::regclass) as rls_expect_true,
  (select count(*) from pg_policies where tablename='account_agreements')               as policies_expect_2,
  (select count(*) from pg_policies where tablename='account_agreements'
     and cmd in ('UPDATE','DELETE','ALL'))                                              as rewrite_policies_expect_0,
  (select count(*) from public.account_agreements)                                      as rows_present,
  (select count(*) from public.account_agreements where agreement_type='terms')          as terms_rows,
  (select count(*) from public.account_agreements where agreement_type='immediate_start') as immediate_start_rows;
