-- ===========================================================================
-- EXPLICIT CONSENT FOR HEALTH AND READINESS INFORMATION
--
-- Valhalla can process optional information the athlete chooses to give it
-- that reveals something about their health -- heart rate, sleep, aches, pain,
-- illness, and how a session felt -- in order to adapt their own training
-- programme. Running a training plan is not a lawful basis for that on its
-- own; it needs the athlete's explicit agreement, and the agreement has to be
-- provable after the fact.
--
-- THIS TABLE IS THE PROOF. One row per decision, never updated and never
-- deleted, so the question "what did this athlete agree to, and when" has an
-- answer that survives them changing their mind, changing device, or
-- restoring an old backup over their local record. The current state is the
-- newest row; everything behind it is the history.
--
-- WHY APPEND-ONLY AND NOT ONE MUTABLE ROW. A single row overwritten on each
-- change answers "do they consent now" and destroys "did they consent on the
-- day that processing happened", which is the question that actually matters
-- if anyone ever asks. The extra cost is a handful of rows per athlete for
-- their entire life on the product.
--
-- WHAT IS NOT HERE. No covered value is stored in this table -- no heart
-- rate, no readiness answer, nothing about the athlete's body. It records a
-- decision and nothing else. It is not an analytics or event stream: nothing
-- writes to it except a deliberate act by the athlete, and nothing reads it
-- except the app itself and the provider-ingest boundary in
-- api/_health-consent.js.
--
-- WHERE IT SITS IN THE ORDER. After supabase-security-posture.sql (file 10),
-- because that file asserts that every table in public has row-level security
-- enabled -- this one is created with RLS on, so re-running 10 afterwards
-- passes rather than refuses.
--
-- Safe to re-run.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- STEP 1 -- THE RECORD
--
-- consent_version is the point of the whole design. Consent is recorded
-- against a named version of the purpose, not against whatever wording
-- happened to be on the screen. If the material purpose of the processing ever
-- changes, the constant changes, every stored agreement to the previous
-- version stops counting, and the athlete is asked again -- with no migration
-- and no backfill, because a version comparison fails closed on its own.
--
-- decided_at is written by the client rather than defaulted to now(), because
-- the decision is made and takes effect on the device -- offline included --
-- and the audit should record when the athlete decided, not when the row
-- happened to reach the database. created_at keeps the server's own view of
-- when it arrived, so the two can be compared if they ever disagree.
-- ---------------------------------------------------------------------------
create table if not exists public.health_data_consent (
  id              bigint generated by default as identity primary key,
  user_id         uuid        not null references auth.users(id) on delete cascade,
  decision        text        not null check (decision in ('granted','withdrawn','declined')),
  consent_version text        not null,
  decided_at      timestamptz not null,
  created_at      timestamptz not null default now()
);

-- The only query the product makes: this athlete's most recent decision.
create index if not exists health_data_consent_user_decided_idx
  on public.health_data_consent (user_id, decided_at desc);

alter table public.health_data_consent enable row level security;


-- ---------------------------------------------------------------------------
-- STEP 2 -- ROW-LEVEL SECURITY
--
-- Two policies, and the shape of them is the whole security posture.
--
--   SELECT own rows. An athlete can see their own consent history, which is
--   their own record and which they are entitled to.
--
--   INSERT own rows. Recording a decision is an insert, and the WITH CHECK
--   pins user_id to the caller, so no client can write a consent record
--   naming somebody else. That is the attack this is actually guarding: a
--   forged "they agreed" row is worse than no row at all.
--
-- THERE IS NO UPDATE POLICY AND NO DELETE POLICY, deliberately. With RLS on
-- and no policy for a command, that command is denied to every browser role.
-- An append-only audit that the audited party can rewrite is not an audit.
-- Erasure, if it is ever decided that withdrawal should also delete the
-- history, is a service-role operation and belongs in its own migration with
-- its own reasoning -- it is not being smuggled in here as a policy.
--
-- (select auth.uid()) rather than a bare auth.uid(), for the InitPlan reason
-- written out in full in supabase-setup.sql and supabase-security-posture.sql.
-- ---------------------------------------------------------------------------
drop policy if exists "own health consent: select" on public.health_data_consent;
drop policy if exists "own health consent: insert" on public.health_data_consent;

create policy "own health consent: select" on public.health_data_consent
  for select using ((select auth.uid()) = user_id);

create policy "own health consent: insert" on public.health_data_consent
  for insert with check ((select auth.uid()) = user_id);


-- ---------------------------------------------------------------------------
-- STEP 3 -- REFUSE IF THE POSTURE IS WRONG
--
-- Everything above is idempotent, so the value of this file on a second run is
-- entirely in what it CHECKS. Three things, each one a way the table could end
-- up wrong without anybody noticing:
--
--   1. RLS off. Every row world-readable with the public anon key.
--   2. An UPDATE or DELETE policy has appeared. The history is now rewritable
--      by the athlete whose consent it records.
--   3. The SELECT or INSERT policy is not scoped to the caller. One athlete
--      can read, or forge, another's consent.
--
-- It raises rather than repairs. A posture that drifted did so for a reason,
-- and silently rewriting it would hide whatever that reason was.
-- ---------------------------------------------------------------------------
do $$
declare
  v_rls   boolean;
  v_bad   text;
  v_open  int;
begin
  select relrowsecurity from pg_class
   where oid = 'public.health_data_consent'::regclass into v_rls;
  if not coalesce(v_rls, false) then
    raise exception using errcode = 'raise_exception',
      message = 'health_data_consent has row-level security OFF. Nothing has been changed.';
  end if;

  select string_agg(policyname || ' (' || cmd || ')', ', ')
    from pg_policies
   where schemaname = 'public' and tablename = 'health_data_consent'
     and cmd in ('UPDATE', 'DELETE', 'ALL')
    into v_bad;
  if v_bad is not null then
    raise exception using errcode = 'raise_exception',
      message = 'health_data_consent must be append-only, but these policies allow '
             || 'rewriting it: ' || v_bad || '. Nothing has been changed.';
  end if;

  -- Every remaining policy must name the caller. A policy whose expression
  -- does not mention auth.uid() is either unscoped or scoped by something
  -- else, and both need a human to look at them.
  select count(*)
    from pg_policies
   where schemaname = 'public' and tablename = 'health_data_consent'
     and coalesce(qual, '') || coalesce(with_check, '') not like '%auth.uid()%'
    into v_open;
  if v_open > 0 then
    raise exception using errcode = 'raise_exception',
      message = 'health_data_consent has ' || v_open || ' policy/policies not scoped to '
             || 'the calling athlete. Nothing has been changed.';
  end if;
end $$;

-- Quick check -- should return rowsecurity = true and exactly two policies,
-- one SELECT and one INSERT:
--   select relrowsecurity from pg_class where relname = 'health_data_consent';
--   select policyname, cmd from pg_policies where tablename = 'health_data_consent';
