// Velvet Viking -- the commercial plan preview.
//
//   POST /api/preview   Authorization: Bearer <supabase access token>
//                       { distanceKey, weeks, volume, schedule, benchmark }
//                       -> a read-only summary of the programme just built
//
// WHY THE ENGINE RUNS HERE. An athlete should see what Valhalla has built for
// them before being asked to pay for it. The obvious way to do that is to hand
// them the app and hide most of it, and that is not a boundary at all: the
// product is one HTML file, so serving it IS giving it away, whatever the UI
// chooses to render.
//
// So the runtime never leaves the server. Its own generator functions are
// loaded into a sandboxed VM here -- exactly the mechanism test/harness.js has
// used all along to exercise real prescriptions without a browser -- and what
// crosses the wire is a summary this file assembles. There is no second
// training engine and nothing to drift: the preview is generated by the same
// code that generates the real thing.
//
// WHAT THE ATHLETE GETS. Enough to recognise the programme as theirs: the goal,
// the shape, the phases, the first week in full, and a handful of the sessions
// that characterise the block.
//
// WHAT THEY DO NOT GET. Anything that makes Valhalla a coach rather than a
// document -- TODAY, Execution Review, adaptation, athlete-state reasoning,
// history, recalibration. Those are the product, and the preview is not
// Valhalla Lite.

'use strict';

const fs = require('fs');
const path = require('path');
const S = require('./_strava.js');
const P = require('./_stripe.js');
const Store = require('./_commercial-store.js');
const Prod = require('./_products.js');

function log(what){ try{ console.log('preview: ' + what); }catch(e){} }

/* The compiled runtime, cached across warm invocations. Parsing twenty thousand
   lines per request would be the difference between a preview and a wait. */
let CACHED = null;

function loadEngine(nowIso){
  const harness = require('../test/harness.js');
  /* The harness is the single place that knows how to load the runtime. Reusing
     it means the preview cannot drift from what the suite exercises -- if the
     app stops loading in a sandbox, the tests fail before production does. */
  return harness.loadApp({ pinnedDate: nowIso });
}

/* ---------- what the client may ask for ----------
   Validated as an allow-list, because these values reach a generator. An
   unbounded `weeks` is a denial-of-service dressed as a training preference.

   THE ALLOW-LIST WAS NOT THE ENGINE'S LIST, and that was a live defect rather
   than a tidiness point. It accepted 'marathon', which DISTANCE_PROFILES has
   never had -- its key is 'full' -- so buildBlockWeeks() threw on volMult and
   every marathon preview returned 503 preview_unavailable. It also rejected
   'full' as an unknown distance, and never offered 'ultra' at all, while the
   builder gateway promises "anything from a 5K to a 50K ultra".

   So the list is now the engine's own DISTANCE_ORDER, and 'marathon' survives
   as an ALIAS that normalises to 'full' -- an older client must not start
   failing to fix a bug it did not cause. What reaches the generator is always
   a key the generator has. */
const DISTANCES = ['5k', '10k', 'half', 'full', 'ultra'];
const DISTANCE_ALIASES = { marathon: 'full' };
/* Which objective the block serves. Same four the builder offers, and
   deliberately NOT recovery: recovery is prescribed after a race Valhalla
   watched, never chosen from a menu, so it can never arrive here. */
const PURPOSES = ['race', 'maintain', 'base', 'speed'];
/* The engine's own shaping, restated as data because the preview has no
   athlete history to read: developmentBlockSpec() derives these from
   absorbedWeeklyVolume(), which for a first-time athlete IS the volume they
   just typed in. Same factors, same default lengths, same forced 5K profile
   for speed -- asserted against the runtime by the test suite so the two
   cannot drift apart in silence. */
const PURPOSE_SHAPE = {
  race:     { weeks: 14, volumeFactor: 1,    forceDistance: null },
  maintain: { weeks: 8,  volumeFactor: 0.75, forceDistance: null },
  base:     { weeks: 10, volumeFactor: 1,    forceDistance: null },
  speed:    { weeks: 6,  volumeFactor: 1,    forceDistance: '5k' }
};
const LIMITS = { weeks: [4, 24], volume: [0, 200], days: [2, 7] };
/* THE SAME THREE TARGETS handleSuggestGoals() offers from a benchmark in the
   canonical builder -- Dream (A), Solid (B), Safety Net (C). The preview
   used to pick training paces straight off the raw benchmark, with no goal
   involved at all, and the athlete never got a say in it; the continuous-
   build bridge then had to invent an active goal on their behalf to build
   their real plan, silently, after they had already authenticated. Neither
   is acceptable for something that changes every training pace in the
   block -- so the choice is asked for here, once, before a preview exists,
   and the same choice is what the real plan is built from later. 'B' is the
   default: it assumes nothing, matching exactly the pace the benchmark
   already demonstrates. */
const GOAL_AMBITIONS = ['A', 'B', 'C'];
const GOAL_AMBITION_MULT = { A: 1.06, B: 1.00, C: 0.94 };

function validate(body){
  const b = body || {};
  const asked = String(b.distanceKey || '').toLowerCase();
  const distanceKey = DISTANCE_ALIASES[asked] || asked;
  if (DISTANCES.indexOf(distanceKey) === -1) return { ok: false, code: 'unknown_distance' };

  /* Absent means race -- every client that predates the objective selector is
     asking for a race block, which is what it always built. */
  const purpose = b.purpose === undefined || b.purpose === null || b.purpose === ''
    ? 'race' : String(b.purpose).toLowerCase();
  if (PURPOSES.indexOf(purpose) === -1) return { ok: false, code: 'unknown_purpose' };

  const weeks = parseInt(b.weeks, 10);
  if (!isFinite(weeks) || weeks < LIMITS.weeks[0] || weeks > LIMITS.weeks[1])
    return { ok: false, code: 'weeks_out_of_range' };

  const volume = Number(b.volume);
  if (!isFinite(volume) || volume < LIMITS.volume[0] || volume > LIMITS.volume[1])
    return { ok: false, code: 'volume_out_of_range' };

  const active = Array.isArray(b.activeDays) ? b.activeDays.map(Number).filter(function(d){
    return isFinite(d) && d >= 0 && d <= 6;
  }) : [];
  const uniq = Array.from(new Set(active));
  if (uniq.length < LIMITS.days[0] || uniq.length > LIMITS.days[1])
    return { ok: false, code: 'training_days_out_of_range' };

  const longRunDay = parseInt(b.longRunDay, 10);
  if (!isFinite(longRunDay) || uniq.indexOf(longRunDay) === -1)
    return { ok: false, code: 'long_run_day_not_a_training_day' };

  const benchSec = parseInt(b.benchmarkSeconds, 10);
  if (!isFinite(benchSec) || benchSec < 300 || benchSec > 40000)
    return { ok: false, code: 'benchmark_out_of_range' };

  /* Absent means 'B' -- an older client that predates this question is
     asking for exactly what the preview always showed: benchmark pace,
     no stretch, no pullback. */
  const goalAmbition = b.goalAmbition === undefined || b.goalAmbition === null || b.goalAmbition === ''
    ? 'B' : String(b.goalAmbition).toUpperCase();
  if (GOAL_AMBITIONS.indexOf(goalAmbition) === -1) return { ok: false, code: 'unknown_goal_ambition' };

  /* THE PURPOSE SHAPES THE BLOCK, HERE, ONCE. Everything downstream reads
     these resolved values, so no later stage has to remember that a speed
     block trains at 5K or that maintenance sits below the athlete's own
     volume. `volume` stays as submitted for the record; `buildVolume` is what
     the generator is given. */
  const shape = PURPOSE_SHAPE[purpose];
  const buildDistance = shape.forceDistance || distanceKey;
  const buildVolume = Math.round(volume * shape.volumeFactor * 10) / 10;

  return { ok: true, input: {
    purpose: purpose,
    distanceKey: distanceKey, buildDistance: buildDistance,
    weeks: weeks, volume: volume, buildVolume: buildVolume,
    /* Only a race block can have an event to aim at. Everything else
       culminates in a goal effort, which is what hasEvent=false means to the
       generator -- the same single switch the app itself uses. */
    hasEvent: purpose === 'race' && b.hasEvent === true,
    activeDays: uniq.sort(), longRunDay: longRunDay, benchmarkSeconds: benchSec,
    goalAmbition: goalAmbition,
    startDate: typeof b.startDate === 'string' ? b.startDate : null
  } };
}
/* The length the builder would have offered for this purpose, so a client that
   omits `weeks` and the app itself agree. Exported for the suite. */
function defaultWeeksFor(purpose){
  const s = PURPOSE_SHAPE[purpose];
  return s ? s.weeks : PURPOSE_SHAPE.race.weeks;
}

/* ---------- the summary ----------
   Assembled explicitly, field by field. Never a spread of the plan: the plan
   object is the product, and a spread is how the product escapes one release
   after somebody adds a field to it. */
function summarise(app, days, blockResult, input){
  const byWeek = {};
  days.forEach(function(d){
    const w = d.week || 1;
    (byWeek[w] = byWeek[w] || []).push(d);
  });
  const weekNumbers = Object.keys(byWeek).map(Number).sort(function(a, b){ return a - b; });

  const dayLine = function(d){
    return {
      weekday: d.dow != null ? d.dow : null,
      date: d.date || null,
      type: d.type || 'rest',
      /* The headline only. Not the full prescription, not the cues, not the
         execution guidance -- those are the coaching. */
      title: d.title || null,
      km: typeof d.km === 'number' ? Math.round(d.km * 10) / 10 : null
    };
  };

  const firstWeek = (byWeek[weekNumbers[0]] || []).map(dayLine);

  /* A few sessions that characterise the block, chosen deterministically: the
     first quality session of each distinct type. Not every session -- the
     complete list of prescriptions is the programme itself. */
  const seen = {};
  const keySessions = [];
  days.forEach(function(d){
    const t = d.type || 'rest';
    if (t === 'rest' || t === 'easy' || seen[t]) return;
    seen[t] = true;
    keySessions.push({ type: t, title: d.title || null, week: d.week || null });
  });

  /* STRUCTURE COMES FROM THE BLOCK, NOT FROM THE DAYS. An earlier version of
     this file read a `phase` field off each day; days do not carry one. The
     block result does carry the shape -- how many weeks build, how many taper,
     and where volume peaks -- which is the same information stated once rather
     than inferred thirty times. */
  const shape = [];
  if (blockResult){
    /* A steady block has one phase because it has one shape. Reporting
       "Build 8 weeks" for maintenance would describe an arc it does not have,
       and "Taper 0 weeks" is already suppressed by the truthiness check. */
    if (blockResult.steady) shape.push({ phase: 'Maintain', weeks: blockResult.planWeeks });
    else {
      if (blockResult.buildWeeks) shape.push({ phase: 'Build', weeks: blockResult.buildWeeks });
      if (blockResult.taperWeeks) shape.push({ phase: 'Taper', weeks: blockResult.taperWeeks });
    }
  }

  const totalKm = days.reduce(function(a, d){ return a + (typeof d.km === 'number' ? d.km : 0); }, 0);

  const purpose = input.purpose || 'race';
  const isRace = purpose === 'race';
  const PURPOSE_COPY = {
    race:     { label: 'Race Build',         says: 'Built to a goal effort at your target distance.' },
    maintain: { label: 'Maintain & Protect', says: 'Holds the fitness you have, at a lower weekly cost.' },
    base:     { label: 'Aerobic Base',       says: 'Builds sustainable capacity from what you already absorb.' },
    speed:    { label: 'Speed & Threshold',  says: 'Sharpens speed and threshold using the 5K session library.' }
  };

  return {
    /* A NON-RACE BLOCK IS NOT SHOWN RACE FIELDS. `raceDate` exists internally
       for every block -- it is the anchor progression counts back from -- but
       presenting it as a race date to somebody building maintenance would be
       inventing an event they never entered. A goal day is offered instead,
       and only a race block gets `raceDate` at all. */
    purpose: {
      key: purpose,
      label: PURPOSE_COPY[purpose].label,
      summary: PURPOSE_COPY[purpose].says,
      hasEvent: !!input.hasEvent
    },
    goal: isRace ? {
      distance: input.distanceKey,
      raceDate: (app.state && app.state.setup && app.state.setup.raceDate) || null
    } : {
      distance: input.buildDistance || input.distanceKey,
      goalDay: (app.state && app.state.setup && app.state.setup.raceDate) || null
    },
    programme: {
      weeks: blockResult && blockResult.planWeeks ? blockResult.planWeeks : input.weeks,
      trainingDaysPerWeek: input.activeDays.length,
      totalSessions: days.filter(function(d){ return (d.type || 'rest') !== 'rest'; }).length,
      totalKm: Math.round(totalKm),
      weeklyVolume: input.buildVolume != null ? input.buildVolume : input.volume
    },
    phases: shape,
    firstWeek: firstWeek,
    keySessions: keySessions.slice(0, 6),
    /* Pace guidance the engine derived for THIS athlete, from their own
       benchmark AND the ambition they chose (Dream/Solid/Safety Net) --
       the same figure the real plan trains at once adopted, so there is
       one set of paces, not a preview set and a different real set. The
       most legible evidence that the programme is theirs and not a
       template. Formatted here; the raw seconds stay on the server. */
    paces: (function(){
      try{
        const mult = GOAL_AMBITION_MULT[input.goalAmbition] || 1;
        const vdot = app.vdotFromPerformance(10000, input.benchmarkSeconds) * mult;
        if (!vdot) return null;
        const z = app.trainingPacesFromVDOT(vdot);
        if (!z) return null;
        const LABEL = { E: 'Easy', M: 'Marathon', T: 'Threshold', I: 'Interval', R: 'Repetition' };
        const out = [];
        ['E', 'M', 'T', 'I'].forEach(function(k){
          const band = z[k];
          if (!band || typeof band.slow !== 'number' || typeof band.fast !== 'number') return;
          out.push({
            zone: LABEL[k] || k,
            range: app.fmtPaceFromSecPerKm(band.slow) + ' – ' + app.fmtPaceFromSecPerKm(band.fast)
          });
        });
        return out.length ? out : null;
      }catch(e){ return null; }
    })()
  };
}

/* ---------- THE GENERATION ITSELF ----------
   Split out of handle() so it can be driven directly. It used to sit inside
   the handler's try block, which meant the only way to reach it was through
   an authenticated HTTP request -- so nothing verified that a maintenance
   preview is actually generated in steady mode, and removing that option
   changed nothing any test could see. A boundary worth having is a boundary
   worth exercising.

   Pure with respect to the request: it takes a loaded engine and a validated
   input, and returns what the summary needs. */
function generate(app, input){
  const startDate = input.startDate || app.todayStr();
  const startMonday = app.addDays(startDate, -app.isoWeekday(startDate));
  const raceDate = app.addDays(startMonday, input.weeks * 7 - 1);
  const schedule = { activeDays: input.activeDays, longRunDay: input.longRunDay };

  /* Maintenance is generated in STEADY mode here for the same reason it is in
     the app: it has no goal effort to taper into, and a preview that showed
     one would be advertising a block the product does not build. */
  const blockResult = app.buildBlockWeeks(input.buildDistance, input.buildVolume, input.weeks,
                                          { steady: input.purpose === 'maintain',
                                            purpose: input.purpose });
  const days = app.buildDaysFromWeeks(blockResult, raceDate, schedule, startDate, input.hasEvent);

  app.state = app.makeDefaultState();
  app.state.setup = {
    distanceKey: input.buildDistance, currentVolume: input.buildVolume, raceDate: raceDate,
    hasEvent: input.hasEvent, purpose: input.purpose,
    startDate: startDate, planWeeks: blockResult.planWeeks, schedule: schedule,
    benchmark: { distanceKey: '10k', timeSec: input.benchmarkSeconds },
    goals: { A: { timeSec: Math.round(input.benchmarkSeconds * 0.95) } }, activeGoal: 'A',
    paceOverrides: {}, lthr: null, maxHR: null, experience: 'experienced'
  };
  app.state.days = days;
  return { app: app, days: days, blockResult: blockResult, startDate: startDate, raceDate: raceDate };
}

/* ---------- what the athlete's REAL plan is built from ----------
   The preview and the real plan must be generated by the exact same call
   with the exact same arguments, or "the plan you saw is the plan you got"
   is a promise this file cannot keep. This is that call, recorded rather
   than re-derived -- the app adopts these verbatim into buildBlockWeeks()/
   buildDaysFromWeeks() once the athlete authenticates, instead of asking
   them to answer the builder a second time. Nothing here is athlete-facing;
   it travels alongside the preview only so the athlete's own device can
   replay their own request. */
function buildEcho(input, startDate, raceDate){
  return {
    purpose: input.purpose, distanceKey: input.buildDistance,
    volume: input.buildVolume, weeks: input.weeks,
    activeDays: input.activeDays, longRunDay: input.longRunDay,
    benchmarkSeconds: input.benchmarkSeconds, benchmarkDistanceKey: '10k',
    goalAmbition: input.goalAmbition,
    hasEvent: input.hasEvent, startDate: startDate, raceDate: raceDate
  };
}

/* ---------- WHAT TO SAY ABOUT THE TRIAL ----------
 *
 * TWO QUESTIONS THAT LOOK LIKE ONE, and conflating them is how this went wrong
 * twice in opposite directions.
 *
 *   "does Valhalla offer a free trial?"      a fact about the OFFER
 *   "may THIS athlete start one?"            a fact about an ATHLETE
 *
 * The endpoint used to answer both with a hardcoded `available: true`, which is
 * a claim about a specific athlete made without looking at that athlete: a
 * returning athlete who had already spent their fortnight was told on the
 * preview screen that one was waiting, and found out otherwise at the payment
 * step. The commercial pass replaced it with the canonical eligibility rule --
 * correct for a signed-in athlete, and wrong the moment the acquisition journey
 * moved the preview IN FRONT of authentication, because an anonymous prospect
 * has no commercial row and the fail-closed answer is "no trial for you",
 * shown to exactly the audience the offer exists for.
 *
 * So the answer depends on whether there is an athlete to ask about:
 *
 *   NO UID   the public offer, from the catalogue. Fourteen days, available.
 *            This is PRESENTATION. It is not a promise to this visitor, and
 *            `resolved: false` says so in the payload rather than in a comment.
 *   A UID    the canonical rule, the same trialEligibility() the checkout seam
 *            and the webhook read, off the same account_commercial row. FAILS
 *            CLOSED: if the commercial core cannot be read, no trial is
 *            offered rather than one we may not be able to honour.
 *
 * NOTHING HERE GRANTS ANYTHING. This response cannot start a trial, cannot
 * consume an allowance and cannot create a subscription. Eligibility is
 * re-decided by mayStartStandardPurchase() when a checkout is opened, and the
 * allowance is spent only when a provider says a trialing subscription exists.
 * An anonymous "available: true" that turns out to be an athlete who already
 * used theirs is refused at the door with `already_used`, exactly as it would
 * have been without this endpoint. See test/webBilling.test.js.
 *
 * NO ATHLETE-SPECIFIC ANSWER IS INFERRED WITHOUT A UID -- there is no branch
 * below that reads a commercial row for an anonymous caller, because there is
 * no athlete for it to be a row about. */
async function trialOffer(cfg, uid){
  if (!uid){
    return { available: true, days: Prod.TRIAL_DAYS, reason: 'anonymous', resolved: false };
  }
  const purchase = await Store.mayStartStandardPurchase(S, cfg, uid, { provider: P.PROVIDER });

  /* BOTH HALVES, AND THE ALLOWANCE ALONE IS NOT ENOUGH.
   *
   * trialEligibility() answers one narrow question -- has this athlete's
   * fortnight been spent -- and an athlete who is ALREADY SUBSCRIBED has
   * usually never spent it. Reading only that half offers a free trial to a
   * paying customer, who then presses the button and is refused at checkout
   * with already_subscribed_here. That is the same dishonesty the hardcoded
   * `true` produced, arriving from the other direction.
   *
   * So the offer is presentable only if the canonical rule says they may start
   * a purchase AT ALL and the allowance is unspent. Both come from one call, so
   * the two answers cannot be taken from different moments. */
  const mayBuy = !!(purchase && purchase.allowed === true);
  const unspent = !!(purchase && purchase.trial && purchase.trial.eligible);
  return {
    available: mayBuy && unspent,
    days: Prod.TRIAL_DAYS,
    /* WHICHEVER HALF ACTUALLY BLOCKED IT, named, so a screen can say the true
       sentence without a second request and without guessing. "You already
       have a subscription" and "you have already used your free trial" are
       different sentences to different people, and one word for both is how a
       support queue fills up. */
    reason: !mayBuy ? ((purchase && purchase.reason) || 'unavailable')
                    : ((purchase.trial && purchase.trial.reason) || 'unavailable'),
    resolved: true
  };
}

async function handle(req, res){
  if (String(req.method || '').toUpperCase() !== 'POST')
    return S.json(res, 405, { error: 'method_not_allowed' });

  /* ANONYMOUS BY DESIGN, NOW. The preview used to require a Bearer token, back
     when authentication came before it in the acquisition journey. Now the
     journey is builder -> preview -> "Save My Plan" -> trial, so a first-time
     visitor reaches this endpoint before they have ever signed in.

     Nothing below actually needed uid for anything but a log line -- generate()
     is a pure function of the validated input, and the comment on GENERATED
     already recorded that no account table is touched here. So widening this
     to "identify the caller if we can, but don't require it" costs nothing:
     a signed-in athlete rebuilding from Plan Settings still gets uid logged,
     and an anonymous visitor gets exactly the same preview they would have
     gotten signed in, because it was always the same computation either way. */
  const cfg = S.config();
  const uid = await S.userIdFromRequest(req, cfg);

  const body = await S.readBody(req);
  const v = validate(body);
  if (!v.ok) return S.json(res, 400, { error: v.code });

  let built;
  try{
    built = generate(loadEngine(new Date().toISOString()), v.input);
  }catch(e){
    /* A code, never the error. A stack from the runtime would describe the
       product's internals to somebody who has not bought it. */
    log('ENGINE_FAILED');
    return S.json(res, 503, { error: 'preview_unavailable' });
  }

  /* GENERATING A PREVIEW MUST NOT SPEND THE TRIAL. Nothing above writes to
     account_commercial, entitlement_grants or subscriptions -- the athlete can
     rebuild as often as they like and their allowance is untouched. The READ
     in trialOffer() below is a read; ensureAccountCommercial is not called and
     no row is created by looking at one. */
  log('GENERATED uid=' + (uid ? String(uid).slice(0, 8) : 'anon') + ' purpose=' + v.input.purpose +
      ' distance=' + v.input.buildDistance);
  const trial = await trialOffer(cfg, uid);
  return S.json(res, 200, {
    preview: summarise(built.app, built.days, built.blockResult, v.input),
    /* The exact arguments that produced the preview above -- see buildEcho().
       The client banks this and, once the athlete authenticates, the app
       replays the same two engine calls verbatim to build their real plan.
       Not part of the athlete-facing preview; never rendered. */
    build: buildEcho(v.input, built.startDate, built.raceDate),
    trial: trial,
    /* Said plainly rather than implied: this is a summary, not the product. */
    note: 'This is a preview of your programme. Valhalla itself coaches it.'
  });
}

module.exports = { handle, validate, summarise, generate, buildEcho, trialOffer, defaultWeeksFor,
                   DISTANCES, DISTANCE_ALIASES, PURPOSES, PURPOSE_SHAPE, LIMITS,
                   GOAL_AMBITIONS, GOAL_AMBITION_MULT };
