// Velvet Viking -- the commercial plan preview.
//
//   POST /api/preview   Authorization: Bearer <supabase access token>
//                       { distanceKey, weeks, volume, schedule, benchmark }
//                       -> a read-only summary of the programme just built
//
// WHY THE ENGINE RUNS HERE. An athlete should see what Valhalla has built for
// them before being asked to pay for it. The obvious way to do that is to hand
// them the app and hide most of it, and that is not a boundary at all: the
// product is one HTML file, so serving it IS giving it away, whatever the UI
// chooses to render.
//
// So the runtime never leaves the server. Its own generator functions are
// loaded into a sandboxed VM here -- exactly the mechanism test/harness.js has
// used all along to exercise real prescriptions without a browser -- and what
// crosses the wire is a summary this file assembles. There is no second
// training engine and nothing to drift: the preview is generated by the same
// code that generates the real thing.
//
// WHAT THE ATHLETE GETS. Enough to recognise the programme as theirs: the goal,
// the shape, the phases, the first week in full, and a handful of the sessions
// that characterise the block.
//
// WHAT THEY DO NOT GET. Anything that makes Valhalla a coach rather than a
// document -- TODAY, Execution Review, adaptation, athlete-state reasoning,
// history, recalibration. Those are the product, and the preview is not
// Valhalla Lite.

'use strict';

const fs = require('fs');
const path = require('path');
const S = require('./_strava.js');
const A = require('./_access.js');

function log(what){ try{ console.log('preview: ' + what); }catch(e){} }

/* The compiled runtime, cached across warm invocations. Parsing twenty thousand
   lines per request would be the difference between a preview and a wait. */
let CACHED = null;

function loadEngine(nowIso){
  const harness = require('../test/harness.js');
  /* The harness is the single place that knows how to load the runtime. Reusing
     it means the preview cannot drift from what the suite exercises -- if the
     app stops loading in a sandbox, the tests fail before production does. */
  return harness.loadApp({ pinnedDate: nowIso });
}

/* ---------- what the client may ask for ----------
   Validated as an allow-list, because these values reach a generator. An
   unbounded `weeks` is a denial-of-service dressed as a training preference. */
const DISTANCES = ['5k', '10k', 'half', 'marathon'];
const LIMITS = { weeks: [4, 24], volume: [0, 200], days: [2, 7] };

function validate(body){
  const b = body || {};
  const distanceKey = String(b.distanceKey || '').toLowerCase();
  if (DISTANCES.indexOf(distanceKey) === -1) return { ok: false, code: 'unknown_distance' };

  const weeks = parseInt(b.weeks, 10);
  if (!isFinite(weeks) || weeks < LIMITS.weeks[0] || weeks > LIMITS.weeks[1])
    return { ok: false, code: 'weeks_out_of_range' };

  const volume = Number(b.volume);
  if (!isFinite(volume) || volume < LIMITS.volume[0] || volume > LIMITS.volume[1])
    return { ok: false, code: 'volume_out_of_range' };

  const active = Array.isArray(b.activeDays) ? b.activeDays.map(Number).filter(function(d){
    return isFinite(d) && d >= 0 && d <= 6;
  }) : [];
  const uniq = Array.from(new Set(active));
  if (uniq.length < LIMITS.days[0] || uniq.length > LIMITS.days[1])
    return { ok: false, code: 'training_days_out_of_range' };

  const longRunDay = parseInt(b.longRunDay, 10);
  if (!isFinite(longRunDay) || uniq.indexOf(longRunDay) === -1)
    return { ok: false, code: 'long_run_day_not_a_training_day' };

  const benchSec = parseInt(b.benchmarkSeconds, 10);
  if (!isFinite(benchSec) || benchSec < 300 || benchSec > 40000)
    return { ok: false, code: 'benchmark_out_of_range' };

  return { ok: true, input: {
    distanceKey: distanceKey, weeks: weeks, volume: volume,
    activeDays: uniq.sort(), longRunDay: longRunDay, benchmarkSeconds: benchSec,
    startDate: typeof b.startDate === 'string' ? b.startDate : null
  } };
}

/* ---------- the summary ----------
   Assembled explicitly, field by field. Never a spread of the plan: the plan
   object is the product, and a spread is how the product escapes one release
   after somebody adds a field to it. */
function summarise(app, days, blockResult, input){
  const byWeek = {};
  days.forEach(function(d){
    const w = d.week || 1;
    (byWeek[w] = byWeek[w] || []).push(d);
  });
  const weekNumbers = Object.keys(byWeek).map(Number).sort(function(a, b){ return a - b; });

  const dayLine = function(d){
    return {
      weekday: d.dow != null ? d.dow : null,
      date: d.date || null,
      type: d.type || 'rest',
      /* The headline only. Not the full prescription, not the cues, not the
         execution guidance -- those are the coaching. */
      title: d.title || null,
      km: typeof d.km === 'number' ? Math.round(d.km * 10) / 10 : null
    };
  };

  const firstWeek = (byWeek[weekNumbers[0]] || []).map(dayLine);

  /* A few sessions that characterise the block, chosen deterministically: the
     first quality session of each distinct type. Not every session -- the
     complete list of prescriptions is the programme itself. */
  const seen = {};
  const keySessions = [];
  days.forEach(function(d){
    const t = d.type || 'rest';
    if (t === 'rest' || t === 'easy' || seen[t]) return;
    seen[t] = true;
    keySessions.push({ type: t, title: d.title || null, week: d.week || null });
  });

  /* STRUCTURE COMES FROM THE BLOCK, NOT FROM THE DAYS. An earlier version of
     this file read a `phase` field off each day; days do not carry one. The
     block result does carry the shape -- how many weeks build, how many taper,
     and where volume peaks -- which is the same information stated once rather
     than inferred thirty times. */
  const shape = [];
  if (blockResult){
    if (blockResult.buildWeeks) shape.push({ phase: 'Build', weeks: blockResult.buildWeeks });
    if (blockResult.taperWeeks) shape.push({ phase: 'Taper', weeks: blockResult.taperWeeks });
  }

  const totalKm = days.reduce(function(a, d){ return a + (typeof d.km === 'number' ? d.km : 0); }, 0);

  return {
    goal: {
      distance: input.distanceKey,
      raceDate: (app.state && app.state.setup && app.state.setup.raceDate) || null
    },
    programme: {
      weeks: blockResult && blockResult.planWeeks ? blockResult.planWeeks : input.weeks,
      trainingDaysPerWeek: input.activeDays.length,
      totalSessions: days.filter(function(d){ return (d.type || 'rest') !== 'rest'; }).length,
      totalKm: Math.round(totalKm)
    },
    phases: shape,
    firstWeek: firstWeek,
    keySessions: keySessions.slice(0, 6),
    /* Pace guidance the engine derived for THIS athlete, from their own
       benchmark. The most legible evidence that the programme is theirs and
       not a template. Formatted here; the raw seconds stay on the server. */
    paces: (function(){
      try{
        const vdot = app.vdotFromPerformance(10000, input.benchmarkSeconds);
        if (!vdot) return null;
        const z = app.trainingPacesFromVDOT(vdot);
        if (!z) return null;
        const LABEL = { E: 'Easy', M: 'Marathon', T: 'Threshold', I: 'Interval', R: 'Repetition' };
        const out = [];
        ['E', 'M', 'T', 'I'].forEach(function(k){
          const band = z[k];
          if (!band || typeof band.slow !== 'number' || typeof band.fast !== 'number') return;
          out.push({
            zone: LABEL[k] || k,
            range: app.fmtPaceFromSecPerKm(band.slow) + ' – ' + app.fmtPaceFromSecPerKm(band.fast)
          });
        });
        return out.length ? out : null;
      }catch(e){ return null; }
    })()
  };
}

async function handle(req, res){
  if (String(req.method || '').toUpperCase() !== 'POST')
    return S.json(res, 405, { error: 'method_not_allowed' });

  const cfg = S.config();
  const uid = await S.userIdFromRequest(req, cfg);
  if (!uid) return S.json(res, 401, { error: 'not_signed_in' });

  const body = await S.readBody(req);
  const v = validate(body);
  if (!v.ok) return S.json(res, 400, { error: v.code });

  let app, days, blockResult;
  try{
    app = loadEngine(new Date().toISOString());
    const startDate = v.input.startDate || app.todayStr();
    const startMonday = app.addDays(startDate, -app.isoWeekday(startDate));
    const raceDate = app.addDays(startMonday, v.input.weeks * 7 - 1);
    const schedule = { activeDays: v.input.activeDays, longRunDay: v.input.longRunDay };

    blockResult = app.buildBlockWeeks(v.input.distanceKey, v.input.volume, v.input.weeks);
    days = app.buildDaysFromWeeks(blockResult, raceDate, schedule, startDate, false);

    app.state = app.makeDefaultState();
    app.state.setup = {
      distanceKey: v.input.distanceKey, currentVolume: v.input.volume, raceDate: raceDate,
      hasEvent: false, startDate: startDate, planWeeks: blockResult.planWeeks, schedule: schedule,
      benchmark: { distanceKey: '10k', timeSec: v.input.benchmarkSeconds },
      goals: { A: { timeSec: Math.round(v.input.benchmarkSeconds * 0.95) } }, activeGoal: 'A',
      paceOverrides: {}, lthr: null, maxHR: null, experience: 'experienced'
    };
    app.state.days = days;
  }catch(e){
    /* A code, never the error. A stack from the runtime would describe the
       product's internals to somebody who has not bought it. */
    log('ENGINE_FAILED');
    return S.json(res, 503, { error: 'preview_unavailable' });
  }

  /* GENERATING A PREVIEW MUST NOT SPEND THE TRIAL. Nothing here writes to
     account_commercial, entitlement_grants or subscriptions -- the athlete can
     rebuild as often as they like and their allowance is untouched. */
  log('generated uid=' + String(uid).slice(0, 8) + ' distance=' + v.input.distanceKey);
  return S.json(res, 200, {
    preview: summarise(app, days, blockResult, v.input),
    trial: { available: true },
    /* Said plainly rather than implied: this is a summary, not the product. */
    note: 'This is a preview of your programme. Valhalla itself coaches it.'
  });
}

module.exports = { handle, validate, summarise, DISTANCES, LIMITS };
